# Generated by Django 4.2.5 on 2023-09-16 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='add_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('dob', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='pending', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('usertype', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('photo', models.FileField(default='', upload_to='')),
                ('dob', models.CharField(default='', max_length=100)),
                ('DEPARTMENT', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.department')),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.login')),
            ],
        ),
        migrations.CreateModel(
            name='sub_allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DEP', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.department')),
                ('STAFF', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.staff')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(default='', max_length=100)),
                ('DEPT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2023-05-01', max_length=100)),
                ('complaint', models.CharField(default='', max_length=100)),
                ('status', models.CharField(default='', max_length=100)),
                ('reply', models.CharField(default='', max_length=100)),
                ('STUDENT_id', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.add_student')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100)),
                ('date', models.CharField(default='', max_length=100)),
                ('STUDENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.add_student')),
            ],
        ),
        migrations.AddField(
            model_name='add_student',
            name='COURSE',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.course'),
        ),
        migrations.AddField(
            model_name='add_student',
            name='LOGIN',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.login'),
        ),
    ]
