# Generated by Django 4.2.5 on 2023-09-16 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collegeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='LOGIN',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.login'),
        ),
    ]
