# Generated by Django 4.2.5 on 2023-09-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Collegeapp', '0002_complaint_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='LOGIN',
        ),
    ]
