# Generated by Django 4.2.5 on 2023-09-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collegeapp', '0003_remove_complaint_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='LOGIN',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Collegeapp.login'),
        ),
    ]
